'use strict';
// 真人 PvP 客户端：服务器裁定伤害、生命、击杀和战功；本地 BOT 战斗仍保持本地模拟。
const NetPlay={ws:null,id:null,room:'frontline',peers:new Map(),lastSend:0,status:'未连接',name:'',
init(){try{this.room=(localStorage.getItem('sf_room')||'frontline').replace(/[^\w-]/g,'').slice(0,24)||'frontline';this.name=localStorage.getItem('sf_name')||'士兵';}catch(e){}},
connect(){if(!Account.ready()){this.status='请先登录';updateNetUI();return;}if(this.ws&&this.ws.readyState<2)return;const base=Account.base();const url=base.replace(/^http/,'ws')+'/';this.status='连接中…';updateNetUI();const ws=this.ws=new WebSocket(url);ws.onopen=()=>{this.status='已连接';this.send({type:'join',room:this.room,name:Account.user(),team:SETTINGS.team,token:Account.token()});updateNetUI();};ws.onmessage=e=>this.receive(e);ws.onclose=()=>{this.status='离线';this.id=null;this.clear();updateNetUI();};ws.onerror=()=>{this.status='连接失败';updateNetUI();};},
send(x){if(this.ws&&this.ws.readyState===1)this.ws.send(JSON.stringify(x));},
receive(e){let m;try{m=JSON.parse(e.data);}catch{return;}if(m.type==='welcome'){this.id=m.id;Account.sync(m.account);(m.players||[]).forEach(p=>this.add(p));}else if(m.type==='auth_error'||m.type==='session_replaced'){Account.clear();this.status='登录已失效';this.ws?.close();alert(m.error||'账号已在另一台设备登录');}else if(m.type==='join')this.add(m.player);else if(m.type==='leave')this.remove(m.id);else if(m.type==='state'&&m.id!==this.id){const p=this.peers.get(m.id);if(p){p.target=m.state;p.hp=m.hp??p.hp;}}else if(m.type==='damage')this.damage(m);},
add(p){if(!p||p.id===this.id||this.peers.has(p.id))return;this.peers.set(p.id,{id:p.id,name:p.name||'士兵',team:p.team===1?1:0,target:p.state||null,hp:p.hp??100,mesh:null,outline:null});},
remove(id){const p=this.peers.get(id);if(p?.mesh)scene.remove(p.mesh.root);this.peers.delete(id);},clear(){[...this.peers.keys()].forEach(id=>this.remove(id));},
damage(m){const target=this.peers.get(m.target);if(target){target.hp=m.hp;if(m.killed&&target.mesh)target.mesh.root.visible=false;}if(m.target===this.id){player.hp=m.hp;if(m.killed){player.alive=false;player.deployed=false;showScorePop('你被敌军击杀');showDeploy(true);}else{dmgFlash=Math.min(1,dmgFlash+.55);AudioSys.hurt();}}if(m.attacker===this.id){player.score=m.score;player.kills=m.kills;if(m.killed){Account.sync({...(Account.account()||{}),credits:m.credits});onPlayerKill({isPlayer:false},m.head,true);}else{onPlayerHit({isPlayer:false},m.head);AudioSys.hitImpact(m.head);}}},
shoot(target,origin,dir,def,head){this.send({type:'shot',target:target.id,ox:origin.x,oy:origin.y,oz:origin.z,dx:dir.x,dy:dir.y,dz:dir.z,dmg:def.dmg,head:!!head});},
tick(dt){if(this.ws?.readyState===1&&performance.now()-this.lastSend>50){this.lastSend=performance.now();this.send({type:'state',state:{x:player.pos.x,y:player.pos.y,z:player.pos.z,yaw:player.yaw,pitch:player.pitch,alive:player.alive,deployed:player.deployed,cls:player.cls}});}for(const p of this.peers.values()){const s=p.target;if(!s||!s.deployed)continue;if(!p.mesh){p.mesh=buildSoldierMesh(p.team,p.name);p.outline=new THREE.BoxHelper(p.mesh.root,0xff2d2d);p.outline.material.depthTest=false;p.outline.material.transparent=true;p.outline.material.opacity=.9;scene.add(p.outline);}p.mesh.root.visible=!!s.alive;if(!s.alive){p.outline.visible=false;continue;}p.mesh.root.position.lerp(V3(s.x,s.y,s.z),Math.min(1,dt*12));p.mesh.root.rotation.y=angleLerpTo(p.mesh.root.rotation.y,s.yaw+Math.PI,dt*10);p.mesh.tag.visible=true;p.mesh.gunG.visible=true;p.mesh.headG.visible=true;p.outline.visible=p.team!==player.team;p.outline.update();}}
};
function updateNetUI(){const e=document.getElementById('netState');if(e)e.textContent='联机：'+NetPlay.status+' · 房间 '+NetPlay.room;}
