'use strict';
// 房主制联机：房主创建六码房间，成员按房间号加入，全部准备后由房主开始。
const NetPlay={ws:null,id:null,room:'',peers:new Map(),lastSend:0,status:'未连接',host:false,ready:false,started:false,config:{campaign:0,hostTeam:0,name:''},onLobbyUpdate:null,
init(){try{this.room=(localStorage.getItem('sf_room')||'').replace(/\D/g,'').slice(0,6);this._resume=localStorage.getItem('sf_pending_room')==='1';}catch(e){}if(this._resume&&this.room)setTimeout(()=>this.connect(),0);},
connect(){if(!Account.ready()){this.status='请先登录';updateNetUI();return;}if(this.ws&&this.ws.readyState<2)return;const url=Account.base().replace(/^http/,'ws')+'/';this.status='连接中…';updateNetUI();const ws=this.ws=new WebSocket(url);ws.onopen=()=>{this.status='已连接';if(this._resume&&this.room){this._resume=false;this.send({type:'join_room',room:this.room,token:Account.token()});}updateNetUI();};ws.onmessage=e=>this.receive(e);ws.onclose=()=>{this.status='离线';this.id=null;this.clear();updateNetUI();};ws.onerror=()=>{this.status='连接失败';updateNetUI();};},
send(x){if(this.ws&&this.ws.readyState===1)this.ws.send(JSON.stringify(x));},
create(name){this.connect();const wait=()=>{if(this.ws?.readyState===1)this.send({type:'create_room',name:String(name||'').trim(),token:Account.token()});else setTimeout(wait,80)};wait();},
join(room){this.room=String(room||'').replace(/\D/g,'').slice(0,6);if(!/^\d{6}$/.test(this.room)){alert('请输入 6 位加入代码');return;}this.connect();const wait=()=>{if(this.ws?.readyState===1)this.send({type:'join_room',room:this.room,token:Account.token()});else setTimeout(wait,80)};wait();},
setReady(){this.send({type:'ready',ready:!this.ready});},
setConfig(c){if(!this.host)return;this.send({type:'room_config',config:c});},
launch(){if(!this.host)return;this.send({type:'start_room'});},
receive(e){let m;try{m=JSON.parse(e.data);}catch{return;}if(m.type==='room_state'||m.type==='welcome_room'){this.id=m.id||this.id;this.room=m.room||this.room;this.host=!!m.host;this.ready=!!m.ready;this.started=!!m.started;this.config={campaign:0,hostTeam:0,name:'',...(m.config||{})};if(Number.isInteger(m.team))player.team=m.team;this.peers.clear();(m.players||[]).forEach(p=>this.add(p));try{localStorage.setItem('sf_room',this.room)}catch{};this.onLobbyUpdate?.();updateNetUI();}
else if(m.type==='room_error'){alert(m.error||'房间操作失败');}
else if(m.type==='match_start'){this.begin(m);}
else if(m.type==='auth_error'||m.type==='session_replaced'){Account.clear();this.status='登录已失效';this.ws?.close();alert(m.error||'账号已在另一台设备登录');}
else if(m.type==='join')this.add(m.player);else if(m.type==='leave')this.remove(m.id);else if(m.type==='state'&&m.id!==this.id){const p=this.peers.get(m.id);if(p){p.target=m.state;p.hp=m.hp??p.hp;}}else if(m.type==='damage')this.damage(m);},
begin(m){this.started=true;this.config=m.config||this.config;const idx=Number(this.config?.campaign);if(Number.isInteger(idx)&&idx!==CAMPAIGN_IDX){localStorage.setItem('sf_campaign',String(idx));localStorage.setItem('sf_pending_room','1');location.reload();return;}localStorage.removeItem('sf_pending_room');SETTINGS.team=m.team===1?1:0;player.team=SETTINGS.team;BOTS_PER_TEAM=SIZE_OPTS[SIZE_IDX].bots;tickets[0]=SIZE_OPTS[SIZE_IDX].tk;tickets[1]=SIZE_OPTS[SIZE_IDX].tk;startMatch();MatchSettlement.start();el('menu').classList.add('hidden');showDeploy(true);},
add(p){if(!p||p.id===this.id||this.peers.has(p.id))return;this.peers.set(p.id,{id:p.id,name:p.name||'士兵',team:p.team===1?1:0,target:p.state||null,hp:p.hp??100,mesh:null,outline:null,ready:!!p.ready});},
remove(id){const p=this.peers.get(id);if(p?.mesh){scene.remove(p.mesh.root);if(p.outline)scene.remove(p.outline);}this.peers.delete(id);},clear(){[...this.peers.keys()].forEach(id=>this.remove(id));},
damage(m){const target=this.peers.get(m.target);if(target){target.hp=m.hp;if(m.killed&&target.mesh)target.mesh.root.visible=false;}if(m.target===this.id){player.hp=m.hp;if(m.killed){player.alive=false;player.deployed=false;showScorePop('你被敌军击杀');showDeploy(true);}else{dmgFlash=Math.min(1,dmgFlash+.55);AudioSys.hurt();}}if(m.attacker===this.id){player.score=m.score;player.kills=m.kills;if(m.killed){Account.sync({...(Account.account()||{}),credits:m.credits});onPlayerKill({isPlayer:false},m.head,true);}else{onPlayerHit({isPlayer:false},m.head);AudioSys.hitImpact(m.head);}}},
shoot(target,origin,dir,def,head){this.send({type:'shot',target:target.id,ox:origin.x,oy:origin.y,oz:origin.z,dx:dir.x,dy:dir.y,dz:dir.z,dmg:def.dmg,head:!!head});},
tick(dt){if(!this.started)return;if(this.ws?.readyState===1&&performance.now()-this.lastSend>50){this.lastSend=performance.now();this.send({type:'state',state:{x:player.pos.x,y:player.pos.y,z:player.pos.z,yaw:player.yaw,pitch:player.pitch,alive:player.alive,deployed:player.deployed,cls:player.cls}});}for(const p of this.peers.values()){const s=p.target;if(!s||!s.deployed)continue;if(!p.mesh){
p.mesh=buildSoldierMesh(p.team,p.name);
}p.mesh.root.visible=!!s.alive;if(!s.alive)continue;p.mesh.root.position.lerp(V3(s.x,s.y,s.z),Math.min(1,dt*12));p.mesh.root.rotation.y=angleLerpTo(p.mesh.root.rotation.y,s.yaw+Math.PI,dt*10);p.mesh.tag.visible=true;p.mesh.gunG.visible=true;p.mesh.headG.visible=true;}}
};
function updateNetUI(){const e=document.getElementById('netState'),members=document.getElementById('netMembers'),code=document.getElementById('netRoom'),name=document.getElementById('netName');if(e)e.textContent='联机：'+NetPlay.status+(NetPlay.room?' · 加入代码 '+NetPlay.room:'');if(code&&NetPlay.room)code.value=NetPlay.room;if(name)name.textContent=NetPlay.config?.name?`房间：${NetPlay.config.name}`:'';if(members){const a=[...NetPlay.peers.values()].map(p=>`${p.name} ${p.ready?'✓':'未准备'}`);members.textContent='成员：'+(NetPlay.id?`${Account.user()} ${NetPlay.ready?'✓':'未准备'}`:'—')+(a.length?' · '+a.join(' · '):'');}const r=document.getElementById('netReadyBtn'),l=document.getElementById('netLaunchBtn');if(r)r.textContent=NetPlay.ready?'取 消 准 备':'准 备';if(l)l.style.display=NetPlay.host?'inline-block':'none';}
