'use strict';
// 本文件由 server/tools/gen_weapon_meta.js 生成，请勿手改；数值改动后重新运行生成器。
// 服务端：裁定伤害/爆头倍率/射速，并复用同一套改装兼容规则。
const WEAPON_META={
 "garand": {
  "name": "M1 加兰德",
  "dmg": 36,
  "headMul": 2.4,
  "rpm": 300,
  "mag": 8,
  "type": "semi",
  "pistol": false,
  "rocket": false,
  "mortar": false,
  "atRifle": false,
  "scoped": false
 },
 "thompson": {
  "name": "汤普森 M1A1",
  "dmg": 21,
  "headMul": 1.8,
  "rpm": 680,
  "mag": 30,
  "type": "auto",
  "pistol": false,
  "rocket": false,
  "mortar": false,
  "atRifle": false,
  "scoped": false
 },
 "bar": {
  "name": "勃朗宁 BAR",
  "dmg": 31,
  "headMul": 1.9,
  "rpm": 480,
  "mag": 20,
  "type": "auto",
  "pistol": false,
  "rocket": false,
  "mortar": false,
  "atRifle": false,
  "scoped": false
 },
 "springfield": {
  "name": "春田 M1903A4",
  "dmg": 96,
  "headMul": 2.5,
  "rpm": 50,
  "mag": 5,
  "type": "bolt",
  "pistol": false,
  "rocket": false,
  "mortar": false,
  "atRifle": false,
  "scoped": true
 },
 "m1911": {
  "name": "柯尔特 M1911",
  "dmg": 26,
  "headMul": 2,
  "rpm": 420,
  "mag": 7,
  "type": "semi",
  "pistol": true,
  "rocket": false,
  "mortar": false,
  "atRifle": false,
  "scoped": false
 },
 "kar98": {
  "name": "毛瑟 Kar98k",
  "dmg": 88,
  "headMul": 2.5,
  "rpm": 52,
  "mag": 5,
  "type": "bolt",
  "pistol": false,
  "rocket": false,
  "mortar": false,
  "atRifle": false,
  "scoped": false
 },
 "kar98zf": {
  "name": "Kar98k ZF41",
  "dmg": 96,
  "headMul": 2.5,
  "rpm": 50,
  "mag": 5,
  "type": "bolt",
  "pistol": false,
  "rocket": false,
  "mortar": false,
  "atRifle": false,
  "scoped": true
 },
 "mp40": {
  "name": "MP40",
  "dmg": 20,
  "headMul": 1.8,
  "rpm": 560,
  "mag": 32,
  "type": "auto",
  "pistol": false,
  "rocket": false,
  "mortar": false,
  "atRifle": false,
  "scoped": false
 },
 "stg44": {
  "name": "STG 44",
  "dmg": 27,
  "headMul": 1.9,
  "rpm": 550,
  "mag": 30,
  "type": "auto",
  "pistol": false,
  "rocket": false,
  "mortar": false,
  "atRifle": false,
  "scoped": false
 },
 "p38": {
  "name": "瓦尔特 P38",
  "dmg": 24,
  "headMul": 2,
  "rpm": 430,
  "mag": 8,
  "type": "semi",
  "pistol": true,
  "rocket": false,
  "mortar": false,
  "atRifle": false,
  "scoped": false
 },
 "m1903": {
  "name": "春田 M1903",
  "dmg": 80,
  "headMul": 2.4,
  "rpm": 54,
  "mag": 5,
  "type": "bolt",
  "pistol": false,
  "rocket": false,
  "mortar": false,
  "atRifle": false,
  "scoped": false
 },
 "bazooka": {
  "name": "巴祖卡 M9",
  "dmg": 24,
  "headMul": 1,
  "rpm": 10,
  "mag": 1,
  "type": "atlauncher",
  "pistol": false,
  "rocket": true,
  "mortar": false,
  "atRifle": false,
  "scoped": false
 },
 "schreck": {
  "name": "坦克杀手 RPzB54",
  "dmg": 24,
  "headMul": 1,
  "rpm": 10,
  "mag": 1,
  "type": "atlauncher",
  "pistol": false,
  "rocket": true,
  "mortar": false,
  "atRifle": false,
  "scoped": false
 },
 "mosin": {
  "name": "莫辛-纳甘 M91/30",
  "dmg": 88,
  "headMul": 2.5,
  "rpm": 50,
  "mag": 5,
  "type": "bolt",
  "pistol": false,
  "rocket": false,
  "mortar": false,
  "atRifle": false,
  "scoped": false
 },
 "mosinpu": {
  "name": "莫辛-纳甘 PU",
  "dmg": 96,
  "headMul": 2.5,
  "rpm": 48,
  "mag": 5,
  "type": "bolt",
  "pistol": false,
  "rocket": false,
  "mortar": false,
  "atRifle": false,
  "scoped": true
 },
 "ppsh": {
  "name": "波波沙 PPSh-41",
  "dmg": 19,
  "headMul": 1.8,
  "rpm": 900,
  "mag": 71,
  "type": "auto",
  "pistol": false,
  "rocket": false,
  "mortar": false,
  "atRifle": false,
  "scoped": false
 },
 "dp28": {
  "name": "捷格加廖夫 DP-28",
  "dmg": 30,
  "headMul": 1.9,
  "rpm": 520,
  "mag": 47,
  "type": "auto",
  "pistol": false,
  "rocket": false,
  "mortar": false,
  "atRifle": false,
  "scoped": false
 },
 "tt33": {
  "name": "托卡列夫 TT-33",
  "dmg": 25,
  "headMul": 2,
  "rpm": 430,
  "mag": 8,
  "type": "semi",
  "pistol": true,
  "rocket": false,
  "mortar": false,
  "atRifle": false,
  "scoped": false
 },
 "ptrd": {
  "name": "PTRD-41 反坦克枪",
  "dmg": 95,
  "headMul": 1.6,
  "rpm": 22,
  "mag": 1,
  "type": "bolt",
  "pistol": false,
  "rocket": false,
  "mortar": false,
  "atRifle": true,
  "scoped": false
 },
 "arisaka": {
  "name": "三八式步枪",
  "dmg": 82,
  "headMul": 2.5,
  "rpm": 54,
  "mag": 5,
  "type": "bolt",
  "pistol": false,
  "rocket": false,
  "mortar": false,
  "atRifle": false,
  "scoped": false
 },
 "type97s": {
  "name": "九七式狙击枪",
  "dmg": 92,
  "headMul": 2.5,
  "rpm": 50,
  "mag": 5,
  "type": "bolt",
  "pistol": false,
  "rocket": false,
  "mortar": false,
  "atRifle": false,
  "scoped": true
 },
 "type100": {
  "name": "一〇〇式冲锋枪",
  "dmg": 19,
  "headMul": 1.8,
  "rpm": 520,
  "mag": 30,
  "type": "auto",
  "pistol": false,
  "rocket": false,
  "mortar": false,
  "atRifle": false,
  "scoped": false
 },
 "type96": {
  "name": "九六式轻机枪",
  "dmg": 28,
  "headMul": 1.9,
  "rpm": 540,
  "mag": 30,
  "type": "auto",
  "pistol": false,
  "rocket": false,
  "mortar": false,
  "atRifle": false,
  "scoped": false
 },
 "nambu": {
  "name": "南部十四年式",
  "dmg": 22,
  "headMul": 2,
  "rpm": 420,
  "mag": 8,
  "type": "semi",
  "pistol": true,
  "rocket": false,
  "mortar": false,
  "atRifle": false,
  "scoped": false
 },
 "type97at": {
  "name": "九七式自动炮",
  "dmg": 90,
  "headMul": 1.5,
  "rpm": 60,
  "mag": 7,
  "type": "semi",
  "pistol": false,
  "rocket": false,
  "mortar": false,
  "atRifle": true,
  "scoped": false
 },
 "zhongzheng": {
  "name": "中正式步骑枪",
  "dmg": 86,
  "headMul": 2.5,
  "rpm": 52,
  "mag": 5,
  "type": "bolt",
  "pistol": false,
  "rocket": false,
  "mortar": false,
  "atRifle": false,
  "scoped": false
 },
 "zhongzhengs": {
  "name": "中正式(狙击)",
  "dmg": 94,
  "headMul": 2.5,
  "rpm": 50,
  "mag": 5,
  "type": "bolt",
  "pistol": false,
  "rocket": false,
  "mortar": false,
  "atRifle": false,
  "scoped": true
 },
 "mp18": {
  "name": "花机关 MP18",
  "dmg": 20,
  "headMul": 1.8,
  "rpm": 500,
  "mag": 32,
  "type": "auto",
  "pistol": false,
  "rocket": false,
  "mortar": false,
  "atRifle": false,
  "scoped": false
 },
 "zb26": {
  "name": "捷克式 ZB-26",
  "dmg": 31,
  "headMul": 1.9,
  "rpm": 500,
  "mag": 20,
  "type": "auto",
  "pistol": false,
  "rocket": false,
  "mortar": false,
  "atRifle": false,
  "scoped": false
 },
 "c96": {
  "name": "驳壳枪 C96",
  "dmg": 24,
  "headMul": 2,
  "rpm": 440,
  "mag": 10,
  "type": "semi",
  "pistol": true,
  "rocket": false,
  "mortar": false,
  "atRifle": false,
  "scoped": false
 },
 "boys": {
  "name": "博伊斯反坦克枪",
  "dmg": 92,
  "headMul": 1.6,
  "rpm": 24,
  "mag": 5,
  "type": "bolt",
  "pistol": false,
  "rocket": false,
  "mortar": false,
  "atRifle": true,
  "scoped": false
 },
 "hanyang": {
  "name": "汉阳造八八式",
  "dmg": 78,
  "headMul": 2.4,
  "rpm": 50,
  "mag": 5,
  "type": "bolt",
  "pistol": false,
  "rocket": false,
  "mortar": false,
  "atRifle": false,
  "scoped": false
 },
 "c96auto": {
  "name": "快慢机(盒子炮)",
  "dmg": 21,
  "headMul": 1.9,
  "rpm": 620,
  "mag": 20,
  "type": "auto",
  "pistol": false,
  "rocket": false,
  "mortar": false,
  "atRifle": false,
  "scoped": false
 },
 "type11": {
  "name": "歪把子(缴获)",
  "dmg": 27,
  "headMul": 1.9,
  "rpm": 480,
  "mag": 30,
  "type": "auto",
  "pistol": false,
  "rocket": false,
  "mortar": false,
  "atRifle": false,
  "scoped": false
 },
 "mortar": {
  "name": "轻型迫击炮",
  "dmg": 30,
  "headMul": 1,
  "rpm": 16,
  "mag": 1,
  "type": "semi",
  "pistol": false,
  "rocket": false,
  "mortar": true,
  "atRifle": false,
  "scoped": false
 },
 "m1carb": {
  "name": "M1 卡宾枪",
  "dmg": 22,
  "headMul": 1.9,
  "rpm": 340,
  "mag": 15,
  "type": "semi",
  "pistol": false,
  "rocket": false,
  "mortar": false,
  "atRifle": false,
  "scoped": false
 },
 "g33": {
  "name": "G33/40 骑枪",
  "dmg": 60,
  "headMul": 2.2,
  "rpm": 48,
  "mag": 5,
  "type": "bolt",
  "pistol": false,
  "rocket": false,
  "mortar": false,
  "atRifle": false,
  "scoped": false
 },
 "m38carb": {
  "name": "莫辛 M38 骑枪",
  "dmg": 62,
  "headMul": 2.2,
  "rpm": 46,
  "mag": 5,
  "type": "bolt",
  "pistol": false,
  "rocket": false,
  "mortar": false,
  "atRifle": false,
  "scoped": false
 },
 "type38c": {
  "name": "三八式骑枪",
  "dmg": 58,
  "headMul": 2.2,
  "rpm": 50,
  "mag": 5,
  "type": "bolt",
  "pistol": false,
  "rocket": false,
  "mortar": false,
  "atRifle": false,
  "scoped": false
 },
 "laotao": {
  "name": "老套筒(汉阳早期)",
  "dmg": 54,
  "headMul": 2.1,
  "rpm": 44,
  "mag": 5,
  "type": "bolt",
  "pistol": false,
  "rocket": false,
  "mortar": false,
  "atRifle": false,
  "scoped": false
 },
 "emp_mg_us": {
  "mag": 99,
  "type": "auto",
  "pistol": false,
  "rocket": false,
  "mortar": false,
  "atRifle": false,
  "scoped": false,
  "vehicle": true,
  "name": "M1919A4 勃朗宁重机枪",
  "dmg": 29,
  "headMul": 1.9,
  "rpm": 520
 },
 "emp_mg_ger": {
  "mag": 99,
  "type": "auto",
  "pistol": false,
  "rocket": false,
  "mortar": false,
  "atRifle": false,
  "scoped": false,
  "vehicle": true,
  "name": "MG42 通用机枪",
  "dmg": 25,
  "headMul": 1.9,
  "rpm": 1100
 },
 "emp_mg_sov": {
  "mag": 99,
  "type": "auto",
  "pistol": false,
  "rocket": false,
  "mortar": false,
  "atRifle": false,
  "scoped": false,
  "vehicle": true,
  "name": "马克沁 M1910 重机枪",
  "dmg": 29,
  "headMul": 1.9,
  "rpm": 560
 },
 "emp_mg_kmt": {
  "mag": 99,
  "type": "auto",
  "pistol": false,
  "rocket": false,
  "mortar": false,
  "atRifle": false,
  "scoped": false,
  "vehicle": true,
  "name": "二四式重机枪",
  "dmg": 30,
  "headMul": 1.9,
  "rpm": 480
 },
 "emp_mg_cpc": {
  "mag": 99,
  "type": "auto",
  "pistol": false,
  "rocket": false,
  "mortar": false,
  "atRifle": false,
  "scoped": false,
  "vehicle": true,
  "name": "二四式重机枪(缴获)",
  "dmg": 30,
  "headMul": 1.9,
  "rpm": 460
 },
 "emp_mg_jp": {
  "mag": 99,
  "type": "auto",
  "pistol": false,
  "rocket": false,
  "mortar": false,
  "atRifle": false,
  "scoped": false,
  "vehicle": true,
  "name": "九二式重机枪",
  "dmg": 32,
  "headMul": 1.9,
  "rpm": 440
 },
 "plane_mg_us_0": {
  "mag": 99,
  "type": "auto",
  "pistol": false,
  "rocket": false,
  "mortar": false,
  "atRifle": false,
  "scoped": false,
  "vehicle": true,
  "name": "P-51 野马 机枪",
  "dmg": 17,
  "headMul": 1.5,
  "rpm": 800
 },
 "plane_mg_us_1": {
  "mag": 99,
  "type": "auto",
  "pistol": false,
  "rocket": false,
  "mortar": false,
  "atRifle": false,
  "scoped": false,
  "vehicle": true,
  "name": "P-47 雷电 机枪",
  "dmg": 21,
  "headMul": 1.5,
  "rpm": 667
 },
 "plane_mg_ger_0": {
  "mag": 99,
  "type": "auto",
  "pistol": false,
  "rocket": false,
  "mortar": false,
  "atRifle": false,
  "scoped": false,
  "vehicle": true,
  "name": "BF-109 机枪",
  "dmg": 17,
  "headMul": 1.5,
  "rpm": 800
 },
 "plane_mg_ger_1": {
  "mag": 99,
  "type": "auto",
  "pistol": false,
  "rocket": false,
  "mortar": false,
  "atRifle": false,
  "scoped": false,
  "vehicle": true,
  "name": "FW-190 机枪",
  "dmg": 21,
  "headMul": 1.5,
  "rpm": 667
 },
 "plane_mg_sov_0": {
  "mag": 99,
  "type": "auto",
  "pistol": false,
  "rocket": false,
  "mortar": false,
  "atRifle": false,
  "scoped": false,
  "vehicle": true,
  "name": "La-5 机枪",
  "dmg": 17,
  "headMul": 1.5,
  "rpm": 800
 },
 "plane_mg_sov_1": {
  "mag": 99,
  "type": "auto",
  "pistol": false,
  "rocket": false,
  "mortar": false,
  "atRifle": false,
  "scoped": false,
  "vehicle": true,
  "name": "IL-2 强击机 机枪",
  "dmg": 22,
  "headMul": 1.5,
  "rpm": 632
 },
 "plane_mg_jp_0": {
  "mag": 99,
  "type": "auto",
  "pistol": false,
  "rocket": false,
  "mortar": false,
  "atRifle": false,
  "scoped": false,
  "vehicle": true,
  "name": "零式舰战 机枪",
  "dmg": 16,
  "headMul": 1.5,
  "rpm": 857
 },
 "plane_mg_jp_1": {
  "mag": 99,
  "type": "auto",
  "pistol": false,
  "rocket": false,
  "mortar": false,
  "atRifle": false,
  "scoped": false,
  "vehicle": true,
  "name": "一式战 隼 机枪",
  "dmg": 20,
  "headMul": 1.5,
  "rpm": 706
 },
 "plane_mg_kmt_0": {
  "mag": 99,
  "type": "auto",
  "pistol": false,
  "rocket": false,
  "mortar": false,
  "atRifle": false,
  "scoped": false,
  "vehicle": true,
  "name": "霍克III 机枪",
  "dmg": 16,
  "headMul": 1.5,
  "rpm": 750
 },
 "plane_mg_kmt_1": {
  "mag": 99,
  "type": "auto",
  "pistol": false,
  "rocket": false,
  "mortar": false,
  "atRifle": false,
  "scoped": false,
  "vehicle": true,
  "name": "伊-16(援华) 机枪",
  "dmg": 19,
  "headMul": 1.5,
  "rpm": 706
 },
 "plane_mg_cpc_0": {
  "mag": 99,
  "type": "auto",
  "pistol": false,
  "rocket": false,
  "mortar": false,
  "atRifle": false,
  "scoped": false,
  "vehicle": true,
  "name": "隼(缴获) 机枪",
  "dmg": 20,
  "headMul": 1.5,
  "rpm": 706
 },
 "plane_mg_cpc_1": {
  "mag": 99,
  "type": "auto",
  "pistol": false,
  "rocket": false,
  "mortar": false,
  "atRifle": false,
  "scoped": false,
  "vehicle": true,
  "name": "九九式(缴获) 机枪",
  "dmg": 19,
  "headMul": 1.5,
  "rpm": 667
 },
 "veh_mg": {
  "mag": 99,
  "type": "auto",
  "pistol": false,
  "rocket": false,
  "mortar": false,
  "atRifle": false,
  "scoped": false,
  "vehicle": true,
  "name": "并列机枪",
  "dmg": 18,
  "headMul": 1.7,
  "rpm": 571
 }
};

function attachmentFitsOn(w,attachId){
 if(!w||w.vehicle)return false;
 const heavy=!!(w.rocket||w.mortar||w.atRifle);
 // 4×镜：装在没有自带瞄具的栓动步枪上（狙击兵的枪本来就自带镜，不重复加装）
 if(attachId==='scope_4x')return !heavy&&w.type==='bolt'&&!w.scoped;
 if(attachId==='silencer')return !heavy&&!!(w.type==='bolt'||w.type==='auto'||w.pistol);
 if(attachId==='extended_mag')return !heavy&&w.mag>1;
 if(attachId==='stock')return !heavy&&!w.pistol;
 return false;
}
function attachmentFits(weaponId,attachId,cls){return attachmentFitsOn(WEAPON_META[weaponId],attachId);}
// 单发最小间隔(ms)：射速留 15% 余量吸收网络抖动。
function minShotInterval(weaponId){
 const w=WEAPON_META[weaponId];
 if(!w)return 1000;
 return Math.max(40,Math.floor(60000/Math.max(30,w.rpm)*0.85));
}
module.exports={WEAPON_META,attachmentFits,attachmentFitsOn,minShotInterval};
